# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bin2bcd_0_0/design_1_bin2bcd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_bin2bcd_0_0 || ORIG_REF_NAME==design_1_bin2bcd_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bin2bcd_0_1/design_1_bin2bcd_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_bin2bcd_0_1 || ORIG_REF_NAME==design_1_bin2bcd_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bin2bcd_0_2/design_1_bin2bcd_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_bin2bcd_0_2 || ORIG_REF_NAME==design_1_bin2bcd_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_1/design_1_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_1 || ORIG_REF_NAME==design_1_xlconcat_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_2/design_1_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_2 || ORIG_REF_NAME==design_1_xlconcat_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_3_0/design_1_xlconcat_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_3_0 || ORIG_REF_NAME==design_1_xlconcat_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_seg7display_0_0/design_1_seg7display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_seg7display_0_0 || ORIG_REF_NAME==design_1_seg7display_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_2_to_1_mux_vector_0_1/design_1_xup_2_to_1_mux_vector_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_2_to_1_mux_vector_0_1 || ORIG_REF_NAME==design_1_xup_2_to_1_mux_vector_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_1/design_1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_1 || ORIG_REF_NAME==design_1_xlslice_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_2/design_1_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_2 || ORIG_REF_NAME==design_1_xlslice_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_2_to_1_mux_vector_0_2/design_1_xup_2_to_1_mux_vector_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_2_to_1_mux_vector_0_2 || ORIG_REF_NAME==design_1_xup_2_to_1_mux_vector_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_2_to_1_mux_vector_0_3/design_1_xup_2_to_1_mux_vector_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_2_to_1_mux_vector_0_3 || ORIG_REF_NAME==design_1_xup_2_to_1_mux_vector_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_dff_vector_0_0/design_1_xup_dff_vector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_dff_vector_0_0 || ORIG_REF_NAME==design_1_xup_dff_vector_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_dff_vector_0_1/design_1_xup_dff_vector_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_dff_vector_0_1 || ORIG_REF_NAME==design_1_xup_dff_vector_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_dff_vector_0_2/design_1_xup_dff_vector_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_dff_vector_0_2 || ORIG_REF_NAME==design_1_xup_dff_vector_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_3_1/design_1_xlconcat_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_3_1 || ORIG_REF_NAME==design_1_xlconcat_3_1} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
