# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_match_password_0_0/design_1_match_password_0_0.xci
# IP: The module: 'design_1_match_password_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_0/design_1_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_0 || ORIG_REF_NAME==design_1_xup_xor2_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_1/design_1_xup_xor2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_1 || ORIG_REF_NAME==design_1_xup_xor2_0_1} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_2/design_1_xup_xor2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_2 || ORIG_REF_NAME==design_1_xup_xor2_0_2} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_3/design_1_xup_xor2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_3 || ORIG_REF_NAME==design_1_xup_xor2_0_3} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_4/design_1_xup_xor2_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_4 || ORIG_REF_NAME==design_1_xup_xor2_0_4} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_5/design_1_xup_xor2_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_5 || ORIG_REF_NAME==design_1_xup_xor2_0_5} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_6/design_1_xup_xor2_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_6 || ORIG_REF_NAME==design_1_xup_xor2_0_6} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_7/design_1_xup_xor2_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_7 || ORIG_REF_NAME==design_1_xup_xor2_0_7} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_8/design_1_xup_xor2_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_8 || ORIG_REF_NAME==design_1_xup_xor2_0_8} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_9/design_1_xup_xor2_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_9 || ORIG_REF_NAME==design_1_xup_xor2_0_9} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_10/design_1_xup_xor2_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_10 || ORIG_REF_NAME==design_1_xup_xor2_0_10} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_11/design_1_xup_xor2_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_11 || ORIG_REF_NAME==design_1_xup_xor2_0_11} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_nor6_0_0/design_1_xup_nor6_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nor6_0_0 || ORIG_REF_NAME==design_1_xup_nor6_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_nor6_0_1/design_1_xup_nor6_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nor6_0_1 || ORIG_REF_NAME==design_1_xup_nor6_0_1} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_and2_0_0/design_1_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_0 || ORIG_REF_NAME==design_1_xup_and2_0_0} -quiet] -quiet

# XDC: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/design_1_ooc.xdc

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_match_password_0_0/design_1_match_password_0_0.xci
# IP: The module: 'design_1_match_password_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_0/design_1_xup_xor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_0 || ORIG_REF_NAME==design_1_xup_xor2_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_1/design_1_xup_xor2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_1 || ORIG_REF_NAME==design_1_xup_xor2_0_1} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_2/design_1_xup_xor2_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_2 || ORIG_REF_NAME==design_1_xup_xor2_0_2} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_3/design_1_xup_xor2_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_3 || ORIG_REF_NAME==design_1_xup_xor2_0_3} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_4/design_1_xup_xor2_0_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_4 || ORIG_REF_NAME==design_1_xup_xor2_0_4} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_5/design_1_xup_xor2_0_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_5 || ORIG_REF_NAME==design_1_xup_xor2_0_5} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_6/design_1_xup_xor2_0_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_6 || ORIG_REF_NAME==design_1_xup_xor2_0_6} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_7/design_1_xup_xor2_0_7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_7 || ORIG_REF_NAME==design_1_xup_xor2_0_7} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_8/design_1_xup_xor2_0_8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_8 || ORIG_REF_NAME==design_1_xup_xor2_0_8} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_9/design_1_xup_xor2_0_9.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_9 || ORIG_REF_NAME==design_1_xup_xor2_0_9} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_10/design_1_xup_xor2_0_10.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_10 || ORIG_REF_NAME==design_1_xup_xor2_0_10} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_xor2_0_11/design_1_xup_xor2_0_11.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_11 || ORIG_REF_NAME==design_1_xup_xor2_0_11} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_nor6_0_0/design_1_xup_nor6_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nor6_0_0 || ORIG_REF_NAME==design_1_xup_nor6_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_nor6_0_1/design_1_xup_nor6_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_nor6_0_1 || ORIG_REF_NAME==design_1_xup_nor6_0_1} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/ip/design_1_xup_and2_0_0/design_1_xup_and2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_0 || ORIG_REF_NAME==design_1_xup_and2_0_0} -quiet] -quiet

# XDC: c:/Users/hatic/Users/hatic/match_password/match_password.srcs/sources_1/bd/design_1/design_1_ooc.xdc
