# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/hatic/Masaüstü/Bays_cons.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_display_and_record_0_0/design_1_display_and_record_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_display_and_record_0_0 || ORIG_REF_NAME==design_1_display_and_record_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_match_password_0_0/design_1_match_password_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_match_password_0_0 || ORIG_REF_NAME==design_1_match_password_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_1/design_1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_1 || ORIG_REF_NAME==design_1_xlslice_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_2/design_1_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_2 || ORIG_REF_NAME==design_1_xlslice_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_3/design_1_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_3 || ORIG_REF_NAME==design_1_xlslice_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_4/design_1_xlslice_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_4 || ORIG_REF_NAME==design_1_xlslice_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_5/design_1_xlslice_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_5 || ORIG_REF_NAME==design_1_xlslice_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_6/design_1_xlslice_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_6 || ORIG_REF_NAME==design_1_xlslice_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_7/design_1_xlslice_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_7 || ORIG_REF_NAME==design_1_xlslice_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_8/design_1_xlslice_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_8 || ORIG_REF_NAME==design_1_xlslice_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_9/design_1_xlslice_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_9 || ORIG_REF_NAME==design_1_xlslice_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_10/design_1_xlslice_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_10 || ORIG_REF_NAME==design_1_xlslice_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_11/design_1_xlslice_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_11 || ORIG_REF_NAME==design_1_xlslice_0_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_dff_0_0/design_1_xup_dff_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_dff_0_0 || ORIG_REF_NAME==design_1_xup_dff_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_dff_1_0/design_1_xup_dff_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_dff_1_0 || ORIG_REF_NAME==design_1_xup_dff_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_0_1/design_1_xup_and2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_1 || ORIG_REF_NAME==design_1_xup_and2_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_0_0/design_1_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_0_0 || ORIG_REF_NAME==design_1_xup_inv_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_1_0/design_1_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_1_0 || ORIG_REF_NAME==design_1_xup_inv_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_2_0/design_1_xup_and2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_2_0 || ORIG_REF_NAME==design_1_xup_and2_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or2_0_1/design_1_xup_or2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or2_0_1 || ORIG_REF_NAME==design_1_xup_or2_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_3_0/design_1_xup_and2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_3_0 || ORIG_REF_NAME==design_1_xup_and2_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_4_0/design_1_xup_and2_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_4_0 || ORIG_REF_NAME==design_1_xup_and2_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debounce_0_0/design_1_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_0_0 || ORIG_REF_NAME==design_1_debounce_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debounce_0_1/design_1_debounce_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_0_1 || ORIG_REF_NAME==design_1_debounce_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_dff_2_0/design_1_xup_dff_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_dff_2_0 || ORIG_REF_NAME==design_1_xup_dff_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debounce_2_0/design_1_debounce_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_2_0 || ORIG_REF_NAME==design_1_debounce_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_5_0/design_1_xup_and2_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_5_0 || ORIG_REF_NAME==design_1_xup_and2_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_5_1/design_1_xup_and2_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_5_1 || ORIG_REF_NAME==design_1_xup_and2_5_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or2_1_0/design_1_xup_or2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or2_1_0 || ORIG_REF_NAME==design_1_xup_or2_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_7_0/design_1_xup_and2_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_7_0 || ORIG_REF_NAME==design_1_xup_and2_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debounce_3_0/design_1_debounce_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_3_0 || ORIG_REF_NAME==design_1_debounce_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_2_0/design_1_xup_inv_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_2_0 || ORIG_REF_NAME==design_1_xup_inv_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_0_0/design_1_xup_and3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and3_0_0 || ORIG_REF_NAME==design_1_xup_and3_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_3_0/design_1_xup_inv_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_3_0 || ORIG_REF_NAME==design_1_xup_inv_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_seg7display_0_0/design_1_seg7display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_seg7display_0_0 || ORIG_REF_NAME==design_1_seg7display_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_2_to_1_mux_vector_0_0/design_1_xup_2_to_1_mux_vector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_2_to_1_mux_vector_0_0 || ORIG_REF_NAME==design_1_xup_2_to_1_mux_vector_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_2_to_1_mux_vector_1_0/design_1_xup_2_to_1_mux_vector_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_2_to_1_mux_vector_1_0 || ORIG_REF_NAME==design_1_xup_2_to_1_mux_vector_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_2_to_1_mux_0_0/design_1_xup_2_to_1_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_2_to_1_mux_0_0 || ORIG_REF_NAME==design_1_xup_2_to_1_mux_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_dff_3_0/design_1_xup_dff_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_dff_3_0 || ORIG_REF_NAME==design_1_xup_dff_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debounce_4_0/design_1_debounce_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_4_0 || ORIG_REF_NAME==design_1_debounce_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_1_0/design_1_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_1_0 || ORIG_REF_NAME==design_1_xup_and2_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_1_0/design_1_xup_and3_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and3_1_0 || ORIG_REF_NAME==design_1_xup_and3_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or2_2_0/design_1_xup_or2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or2_2_0 || ORIG_REF_NAME==design_1_xup_or2_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_8_0/design_1_xup_and2_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_8_0 || ORIG_REF_NAME==design_1_xup_and2_8_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_4_0/design_1_xup_inv_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_4_0 || ORIG_REF_NAME==design_1_xup_inv_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_5_0/design_1_xup_inv_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_5_0 || ORIG_REF_NAME==design_1_xup_inv_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_dff_4_0/design_1_xup_dff_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_dff_4_0 || ORIG_REF_NAME==design_1_xup_dff_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_2_0/design_1_xup_and3_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and3_2_0 || ORIG_REF_NAME==design_1_xup_and3_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_6_0/design_1_xup_inv_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_6_0 || ORIG_REF_NAME==design_1_xup_inv_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_time_ended_0_0/design_1_time_ended_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_time_ended_0_0 || ORIG_REF_NAME==design_1_time_ended_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_dff_5_0/design_1_xup_dff_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_dff_5_0 || ORIG_REF_NAME==design_1_xup_dff_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_dff_6_0/design_1_xup_dff_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_dff_6_0 || ORIG_REF_NAME==design_1_xup_dff_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or3_1_0/design_1_xup_or3_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or3_1_0 || ORIG_REF_NAME==design_1_xup_or3_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_4_0/design_1_xup_and3_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and3_4_0 || ORIG_REF_NAME==design_1_xup_and3_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or3_0_1/design_1_xup_or3_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or3_0_1 || ORIG_REF_NAME==design_1_xup_or3_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_5_0/design_1_xup_and3_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and3_5_0 || ORIG_REF_NAME==design_1_xup_and3_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or4_0_0/design_1_xup_or4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or4_0_0 || ORIG_REF_NAME==design_1_xup_or4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_13_1/design_1_xup_and2_13_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_13_1 || ORIG_REF_NAME==design_1_xup_and2_13_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_9_0/design_1_xup_and2_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_9_0 || ORIG_REF_NAME==design_1_xup_and2_9_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or2_3_1/design_1_xup_or2_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or2_3_1 || ORIG_REF_NAME==design_1_xup_or2_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_6_1/design_1_xup_and3_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and3_6_1 || ORIG_REF_NAME==design_1_xup_and3_6_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_7_1/design_1_xup_and3_7_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and3_7_1 || ORIG_REF_NAME==design_1_xup_and3_7_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_10_0/design_1_xup_and2_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_10_0 || ORIG_REF_NAME==design_1_xup_and2_10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or2_4_0/design_1_xup_or2_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or2_4_0 || ORIG_REF_NAME==design_1_xup_or2_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_3_0/design_1_xup_and3_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and3_3_0 || ORIG_REF_NAME==design_1_xup_and3_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_3_1/design_1_xup_and3_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and3_3_1 || ORIG_REF_NAME==design_1_xup_and3_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_clk_divider_0_0/design_1_xup_clk_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_clk_divider_0_0 || ORIG_REF_NAME==design_1_xup_clk_divider_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or3_2_0/design_1_xup_or3_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or3_2_0 || ORIG_REF_NAME==design_1_xup_or3_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_7_0/design_1_xup_inv_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_7_0 || ORIG_REF_NAME==design_1_xup_inv_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_2_to_1_mux_1_0/design_1_xup_2_to_1_mux_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_2_to_1_mux_1_0 || ORIG_REF_NAME==design_1_xup_2_to_1_mux_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_clk_divider_1_0/design_1_xup_clk_divider_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_clk_divider_1_0 || ORIG_REF_NAME==design_1_xup_clk_divider_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or5_0_0/design_1_xup_or5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or5_0_0 || ORIG_REF_NAME==design_1_xup_or5_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_2_to_1_mux_2_0/design_1_xup_2_to_1_mux_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_2_to_1_mux_2_0 || ORIG_REF_NAME==design_1_xup_2_to_1_mux_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or3_3_0/design_1_xup_or3_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or3_3_0 || ORIG_REF_NAME==design_1_xup_or3_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_2_to_1_mux_3_0/design_1_xup_2_to_1_mux_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_2_to_1_mux_3_0 || ORIG_REF_NAME==design_1_xup_2_to_1_mux_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or2_5_0/design_1_xup_or2_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or2_5_0 || ORIG_REF_NAME==design_1_xup_or2_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_2_to_1_mux_4_0/design_1_xup_2_to_1_mux_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_2_to_1_mux_4_0 || ORIG_REF_NAME==design_1_xup_2_to_1_mux_4_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
