# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_display_and_record_0_0/design_1_display_and_record_0_0.xci
# IP: The module: 'design_1_display_and_record_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_bin2bcd_0_0/design_1234_bin2bcd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_bin2bcd_0_0 || ORIG_REF_NAME==design_1234_bin2bcd_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_bin2bcd_1_0/design_1234_bin2bcd_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_bin2bcd_1_0 || ORIG_REF_NAME==design_1234_bin2bcd_1_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_bin2bcd_2_0/design_1234_bin2bcd_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_bin2bcd_2_0 || ORIG_REF_NAME==design_1234_bin2bcd_2_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_seg7display_0_0/design_1234_seg7display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_seg7display_0_0 || ORIG_REF_NAME==design_1234_seg7display_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlconcat_0_0/design_1234_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlconcat_0_0 || ORIG_REF_NAME==design_1234_xlconcat_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlconcat_1_0/design_1234_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlconcat_1_0 || ORIG_REF_NAME==design_1234_xlconcat_1_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlconcat_2_0/design_1234_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlconcat_2_0 || ORIG_REF_NAME==design_1234_xlconcat_2_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlconcat_3_0/design_1234_xlconcat_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlconcat_3_0 || ORIG_REF_NAME==design_1234_xlconcat_3_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlconcat_4_0/design_1234_xlconcat_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlconcat_4_0 || ORIG_REF_NAME==design_1234_xlconcat_4_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlconstant_0_0/design_1234_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlconstant_0_0 || ORIG_REF_NAME==design_1234_xlconstant_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlconstant_1_0/design_1234_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlconstant_1_0 || ORIG_REF_NAME==design_1234_xlconstant_1_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlslice_0_0/design_1234_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlslice_0_0 || ORIG_REF_NAME==design_1234_xlslice_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlslice_1_0/design_1234_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlslice_1_0 || ORIG_REF_NAME==design_1234_xlslice_1_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlslice_2_0/design_1234_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlslice_2_0 || ORIG_REF_NAME==design_1234_xlslice_2_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xup_2_to_1_mux_vector_0_0/design_1234_xup_2_to_1_mux_vector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xup_2_to_1_mux_vector_0_0 || ORIG_REF_NAME==design_1234_xup_2_to_1_mux_vector_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xup_2_to_1_mux_vector_1_0/design_1234_xup_2_to_1_mux_vector_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xup_2_to_1_mux_vector_1_0 || ORIG_REF_NAME==design_1234_xup_2_to_1_mux_vector_1_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xup_2_to_1_mux_vector_2_0/design_1234_xup_2_to_1_mux_vector_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xup_2_to_1_mux_vector_2_0 || ORIG_REF_NAME==design_1234_xup_2_to_1_mux_vector_2_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xup_dff_vector_0_0/design_1234_xup_dff_vector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xup_dff_vector_0_0 || ORIG_REF_NAME==design_1234_xup_dff_vector_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xup_dff_vector_1_0/design_1234_xup_dff_vector_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xup_dff_vector_1_0 || ORIG_REF_NAME==design_1234_xup_dff_vector_1_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xup_dff_vector_2_0/design_1234_xup_dff_vector_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xup_dff_vector_2_0 || ORIG_REF_NAME==design_1234_xup_dff_vector_2_0} -quiet] -quiet

# XDC: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/design_1234_ooc.xdc

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_display_and_record_0_0/design_1_display_and_record_0_0.xci
# IP: The module: 'design_1_display_and_record_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_bin2bcd_0_0/design_1234_bin2bcd_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_bin2bcd_0_0 || ORIG_REF_NAME==design_1234_bin2bcd_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_bin2bcd_1_0/design_1234_bin2bcd_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_bin2bcd_1_0 || ORIG_REF_NAME==design_1234_bin2bcd_1_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_bin2bcd_2_0/design_1234_bin2bcd_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_bin2bcd_2_0 || ORIG_REF_NAME==design_1234_bin2bcd_2_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_seg7display_0_0/design_1234_seg7display_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_seg7display_0_0 || ORIG_REF_NAME==design_1234_seg7display_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlconcat_0_0/design_1234_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlconcat_0_0 || ORIG_REF_NAME==design_1234_xlconcat_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlconcat_1_0/design_1234_xlconcat_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlconcat_1_0 || ORIG_REF_NAME==design_1234_xlconcat_1_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlconcat_2_0/design_1234_xlconcat_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlconcat_2_0 || ORIG_REF_NAME==design_1234_xlconcat_2_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlconcat_3_0/design_1234_xlconcat_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlconcat_3_0 || ORIG_REF_NAME==design_1234_xlconcat_3_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlconcat_4_0/design_1234_xlconcat_4_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlconcat_4_0 || ORIG_REF_NAME==design_1234_xlconcat_4_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlconstant_0_0/design_1234_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlconstant_0_0 || ORIG_REF_NAME==design_1234_xlconstant_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlconstant_1_0/design_1234_xlconstant_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlconstant_1_0 || ORIG_REF_NAME==design_1234_xlconstant_1_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlslice_0_0/design_1234_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlslice_0_0 || ORIG_REF_NAME==design_1234_xlslice_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlslice_1_0/design_1234_xlslice_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlslice_1_0 || ORIG_REF_NAME==design_1234_xlslice_1_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xlslice_2_0/design_1234_xlslice_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xlslice_2_0 || ORIG_REF_NAME==design_1234_xlslice_2_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xup_2_to_1_mux_vector_0_0/design_1234_xup_2_to_1_mux_vector_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xup_2_to_1_mux_vector_0_0 || ORIG_REF_NAME==design_1234_xup_2_to_1_mux_vector_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xup_2_to_1_mux_vector_1_0/design_1234_xup_2_to_1_mux_vector_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xup_2_to_1_mux_vector_1_0 || ORIG_REF_NAME==design_1234_xup_2_to_1_mux_vector_1_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xup_2_to_1_mux_vector_2_0/design_1234_xup_2_to_1_mux_vector_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xup_2_to_1_mux_vector_2_0 || ORIG_REF_NAME==design_1234_xup_2_to_1_mux_vector_2_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xup_dff_vector_0_0/design_1234_xup_dff_vector_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xup_dff_vector_0_0 || ORIG_REF_NAME==design_1234_xup_dff_vector_0_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xup_dff_vector_1_0/design_1234_xup_dff_vector_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xup_dff_vector_1_0 || ORIG_REF_NAME==design_1234_xup_dff_vector_1_0} -quiet] -quiet

# IP: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/ip/design_1234_xup_dff_vector_2_0/design_1234_xup_dff_vector_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1234_xup_dff_vector_2_0 || ORIG_REF_NAME==design_1234_xup_dff_vector_2_0} -quiet] -quiet

# XDC: c:/Users/hatic/Users/hatic/display_and_record/display_and_record.srcs/sources_1/bd/design_1234/design_1234_ooc.xdc
