# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/design_1_time_ended_0_0.xci
# IP: The module: 'design_1_time_ended_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_c_counter_binary_0_0/design_123_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_c_counter_binary_0_0 || ORIG_REF_NAME==design_123_c_counter_binary_0_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xlconstant_0_0/design_123_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xlconstant_0_0 || ORIG_REF_NAME==design_123_xlconstant_0_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xlconstant_1_0/design_123_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xlconstant_1_0 || ORIG_REF_NAME==design_123_xlconstant_1_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xlslice_0_0/design_123_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xlslice_0_0 || ORIG_REF_NAME==design_123_xlslice_0_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xlslice_1_0/design_123_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xlslice_1_0 || ORIG_REF_NAME==design_123_xlslice_1_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xlslice_2_0/design_123_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xlslice_2_0 || ORIG_REF_NAME==design_123_xlslice_2_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xlslice_3_0/design_123_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xlslice_3_0 || ORIG_REF_NAME==design_123_xlslice_3_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xlslice_4_0/design_123_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xlslice_4_0 || ORIG_REF_NAME==design_123_xlslice_4_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xup_clk_divider_0_0/design_123_xup_clk_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xup_clk_divider_0_0 || ORIG_REF_NAME==design_123_xup_clk_divider_0_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xup_nor5_0_0/design_123_xup_nor5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xup_nor5_0_0 || ORIG_REF_NAME==design_123_xup_nor5_0_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xup_xor2_0_0/design_123_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xup_xor2_0_0 || ORIG_REF_NAME==design_123_xup_xor2_0_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xup_xor2_1_0/design_123_xup_xor2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xup_xor2_1_0 || ORIG_REF_NAME==design_123_xup_xor2_1_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xup_xor2_2_0/design_123_xup_xor2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xup_xor2_2_0 || ORIG_REF_NAME==design_123_xup_xor2_2_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xup_xor2_3_0/design_123_xup_xor2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xup_xor2_3_0 || ORIG_REF_NAME==design_123_xup_xor2_3_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xup_xor2_4_0/design_123_xup_xor2_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xup_xor2_4_0 || ORIG_REF_NAME==design_123_xup_xor2_4_0} -quiet] -quiet

# XDC: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/design_123_ooc.xdc

# IP: C:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/design_1_time_ended_0_0.xci
# IP: The module: 'design_1_time_ended_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_c_counter_binary_0_0/design_123_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_c_counter_binary_0_0 || ORIG_REF_NAME==design_123_c_counter_binary_0_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xlconstant_0_0/design_123_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xlconstant_0_0 || ORIG_REF_NAME==design_123_xlconstant_0_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xlconstant_1_0/design_123_xlconstant_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xlconstant_1_0 || ORIG_REF_NAME==design_123_xlconstant_1_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xlslice_0_0/design_123_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xlslice_0_0 || ORIG_REF_NAME==design_123_xlslice_0_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xlslice_1_0/design_123_xlslice_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xlslice_1_0 || ORIG_REF_NAME==design_123_xlslice_1_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xlslice_2_0/design_123_xlslice_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xlslice_2_0 || ORIG_REF_NAME==design_123_xlslice_2_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xlslice_3_0/design_123_xlslice_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xlslice_3_0 || ORIG_REF_NAME==design_123_xlslice_3_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xlslice_4_0/design_123_xlslice_4_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xlslice_4_0 || ORIG_REF_NAME==design_123_xlslice_4_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xup_clk_divider_0_0/design_123_xup_clk_divider_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xup_clk_divider_0_0 || ORIG_REF_NAME==design_123_xup_clk_divider_0_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xup_nor5_0_0/design_123_xup_nor5_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xup_nor5_0_0 || ORIG_REF_NAME==design_123_xup_nor5_0_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xup_xor2_0_0/design_123_xup_xor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xup_xor2_0_0 || ORIG_REF_NAME==design_123_xup_xor2_0_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xup_xor2_1_0/design_123_xup_xor2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xup_xor2_1_0 || ORIG_REF_NAME==design_123_xup_xor2_1_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xup_xor2_2_0/design_123_xup_xor2_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xup_xor2_2_0 || ORIG_REF_NAME==design_123_xup_xor2_2_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xup_xor2_3_0/design_123_xup_xor2_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xup_xor2_3_0 || ORIG_REF_NAME==design_123_xup_xor2_3_0} -quiet] -quiet

# IP: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/ip/design_123_xup_xor2_4_0/design_123_xup_xor2_4_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_123_xup_xor2_4_0 || ORIG_REF_NAME==design_123_xup_xor2_4_0} -quiet] -quiet

# XDC: c:/Users/hatic/deigit_des/deigit_des.srcs/sources_1/bd/design_1/ip/design_1_time_ended_0_0/design_123_ooc.xdc
